name: mangabackupconverter
description: An opinionated template for a Flutter project.

publish_to: none

version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0 <4.0.0"

dependencies:
  accessibility_tools: ^2.2.2
  assets:
    path: packages/assets
  awesome_flutter_extensions: ^1.2.0
  collection: ^1.18.0
  connectivity_plus: ^6.0.2
  constants:
    path: packages/constants
  cupertino_icons: ^1.0.6
  dart_mappable: ^4.1.0
  env:
    path: packages/env
  flex_color_picker: ^3.4.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.2.6
  flutter_flavor: ^3.1.1
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.0
  flutter_settings_ui: ^3.0.1
  flutter_web_plugins:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.2.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.4.9
  http: ^1.2.0
  localization:
    path: packages/localization
  logging: ^1.2.0
  modddels_annotation_fpdart: ^0.2.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod: ^2.3.6
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  skeletonizer: ^1.1.1
  stock: ^1.0.1
  super_clipboard: ^0.8.22
  universal_html: ^2.2.4
  url_launcher: ^6.2.6
  window_manager: ^0.4.2
  wolt_modal_sheet: ^0.9.2

dev_dependencies:
  app_lints:
    path: packages/app_lints
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  change_app_package_name: ^1.1.0
  custom_lint: ^0.6.4
  dart_mappable_builder: ^4.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  integration_test:
    sdk: flutter
  mason: ^0.1.0-dev.52
  melos: ^6.1.0
  mocktail: ^1.0.3
  modddels: ^0.2.0
  msix: ^3.16.7
  patrol: ^3.6.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  solid_lints: ^0.1.5
  sqflite_common_ffi_web: ^0.4.3+1
  test: any

flutter:
  uses-material-design: true

msix_config:
  display_name: Flutter Template App
  install_certificate: false

patrol:
  app_name: Manga Backup Converter
  android:
    package_name: dev.getboolean.mangabackupconverter
  ios:
    bundle_id: dev.getboolean.mangabackupconverter
